### ISSUE TITLE
How to get new fingerprint?

### ISSUE THREAD

**Issue by awaisnajam** [electronicsguy/ESP8266#34]
Hello Sujay,

I am trying to use your library to post data to google spreedsheet. But I am getting the following error.

Connecting to script.google.com
Connection Status: 1
Certificate mis-match

Please, let us know how to get a new matching fingerprint.

Regards,
Awais

**Comment by electronicsguy** [comment]
As mentioned in the readme, the fingerprint check is not mandatory. Dis-regard the fingerprint check for now and see if you're able to successfully read/write to Google Sheets. This message is a warning, not a error.

To get a new fingerprint, please follow the procedure listed in the Readme. You must run openssl from the same network location where your device will be (since Google servers serve requests from different servers internally, based on geo-location).  Comment out the certificate check code and let me know if you're able to read/write successfully.

**Comment by awaisnajam** [comment]
Hello Sujay,
Thank you for your guidance. Now, I am able to read /write the Google Sheet "ESP8266 Logging" using version 2.1 of HTTPSRedirect.
Fingerprint issue is still there which I will follow later.
Regards,
Awais

**Comment by electronicsguy** [comment]
great. all the best.
