### ISSUE TITLE
client.verify() removed

### ISSUE THREAD

**Issue by zenmanenergy** [electronicsguy/ESP8266#46]
These lines throw an error on esp32:
https://github.com/electronicsguy/ESP8266/blob/master/HTTPSRedirect/GoogleDocs.ino#L107-L111

Looks like WifiClientSecure has no verify method in the esp32 core as it is a security risk. 

https://github.com/espressif/arduino-esp32/issues/278

**Comment by electronicsguy** [comment]
Yes that method has been removed. but there are many more issue to resolve before I can make it work reliably on ESP32, with the new mbedTLS. At the moment, it works with one-way communication, not duplex. Will update as I can solve them in the coming weeks.

**Comment by zenmanenergy** [comment]
That's sounds pretty great. Yesterday I was playing around with the google oAuth stuff. It would be cool if we could figure out how to do this with secured spreadsheets instead of the "anyone can edit" sharing option.

**Comment by electronicsguy** [comment]
@zenmanenergy   the whole problem with oAuth (which this solves) is it's unnecessarily complex for most people. Plus this is still maintaining security within Google's bubble: as long as you keep your spreadsheet id secret. I didn't want to go down the oAuth route since it reduces flexibility, increases complexity without any real benefit for IoT users.
