### ISSUE TITLE
Compilation error from ANir's water sensor project 

### ISSUE THREAD

**Issue by RockOrSomething** [electronicsguy/ESP8266#50]
Hello, Sujay!  I am trying to get code from [ANir's water sensor project ](http://embedded-lab.com/blog/post-data-google-sheets-using-esp8266/#comment-2315927) to compile but am getting an error: 

exit status 1
no matching function for call to 'HTTPSRedirect::printRedir(String&, const char*&, const char*&)'

I see in the HTTPSRedirect.h library the following printRedir() function:
bool printRedir(void);    

...the code, however, calls for (String, char, char) arguments.  

Am I doing something wrong here, or has there been an update to the library that needs a corresponding update to ANir's code?

**Comment by electronicsguy** [comment]
@RockOrSomething   Hi, as I mentioned in the comments on that page, the code there is outdated. (it's always a problem when people paste code rather than linking to the original). The author hasn't updated it since I release V2 of this library.

Please follow the instructions in the Readme and see the example to understand how it works. You no longer call printRedir() directly. You'll have to modify the sensor recording code accordingly for your needs.

If you face any issues with the example, please post them here.
